name: Update Taipei Time JSON

on:
  schedule:
    - cron: "*/5 * * * *"     # 每 5 分鐘自動
  workflow_dispatch:          # 也可手動按

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate now.json (bash only; no heredoc)
        run: |
          set -e
          UTC_NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TPE_NOW=$(TZ=Asia/Taipei date +"%Y-%m-%dT%H:%M:%S%z")
          TPE_NOW_ISO="${TPE_NOW:0:22}:${TPE_NOW:22:2}"
          UNIX_TS=$(date -u +%s)
          RUN_ID="${GITHUB_RUN_ID}"

          printf '%s\n' \
            '{' \
            '  "source": "GitHub Actions (cron)",' \
            '  "timezone": "Asia/Taipei",' \
            "  \"taipei_iso\": \"${TPE_NOW_ISO}\"," \
            "  \"unix\": ${UNIX_TS}," \
            "  \"generated_utc\": \"${UTC_NOW}\"," \
            "  \"generated_taipei\": \"${TPE_NOW_ISO}\"," \
            "  \"run_id\": \"${RUN_ID}\"," \
            '  "version": "1.0.1"' \
            '}' > now.json

          echo "===== now.json ====="
          cat now.json

      - name: Commit & Push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 先讓 pull 時自動 stash 目前未提交的變更（now.json）
          git -c rebase.autoStash=true pull --rebase || true

          git add now.json
          git commit -m "auto: update now.json (run $GITHUB_RUN_ID)" || echo "No changes"
          git push

